<?php 
$request = $this->getRequest()->getParams();
$jsonFile = "";
if (isset($request['json']) && $request['json'] != "") {
	$jsonFile = "json/" . $request['json'];
}
?>
<style>
	.loader {
		background: url("<?php echo $this->getJsUrl("pdp/images/gif-load.gif"); ?>") no-repeat scroll center center rgba(0, 0, 0, 0);
    	text-align: center;
    	padding: 20px;
    	 margin-top: 50px;
	}
</style>
<div class="iframe-container" style="display: none;">
	<button style="display: none;" id="get_design_content">Get Design Page</button>
	<span id="close_iframe" class="close"></span>
	<div class="pdc_design_panel"></div>
</div>
<div class="loader"></div>
<script src="<?php echo $this->getJSUrl('pdp/js/jquery.min.js') ?>"></script>
<script src="<?php echo $this->getJSUrl('pdp/js/farbtastic.js') ?>"></script>
<script src="<?php echo $this->getJSUrl('pdp/js/jquery.nouislider.js') ?>"></script>
<script src="<?php echo $this->getJSUrl('pdp/js/owl.carousel.js') ?>"></script>
<script src="<?php echo $this->getJSUrl('pdp/js/fabric.js') ?>"></script>
<script src="<?php echo $this->getJSUrl('pdp/js/jquery.mCustomScrollbar.concat.min.js') ?>"></script>
<script>
	jQuery(function($) {
		var mainWindow = top.document;
		var baseUrl = $("#base_url", mainWindow).val(),
			_ifMarginTop = "10px", 
			productId = "<?php echo $request['product-id']?>";
		LoadDesign = {
			pendingTime : 0,
			baseUrl : null,
			init : function() {
				setTimeout(function() {
					LoadDesign.getDesignPage();
				}, LoadDesign.pendingTime);
			},
			getDesignPage : function() {
				var designUrl = baseUrl + "pdp/view/getDesignPage/product-id/" + productId + "/area/customize/" + "<?php echo $jsonFile?>";
				LoadDesign.sendRequest(designUrl, function(response) {
					if (response != "") {
						$(".pdc_design_panel").html(response);
						LoadDesign.resizeIframe();
					}
				});
			},
			sendRequest : function(url, callback) {
				$.ajax({
					type : "GET",
					url : url,
					beforeSend : function () {
						//console.log("Sending request...");
						$(".pdp_loading").show();
					},
					success : function(data) {
						callback(data);
						$(".pdp_loading").hide();
					}
				});
			},
			resizeIframe : function() {
				console.log("Resize Iframe");
				var _iframeWPercent = 90,
					_iframeHPercent = 80,
					_screenW = screen.availWidth,
					_screenH = screen.availHeight;
				if (screen.availWidth <= 1024) {
					_iframeWPercent = 100;
				}
				var iframeWidth = (_screenW * _iframeWPercent) / 100;
				var iframeHeight = (_screenH * _iframeHPercent) / 100;
				console.log(iframeWidth, iframeHeight, $(".pdc_design_panel")[0].scrollHeight);
				//$("#pdc_iframe", mainWindow).attr("width", $(".pdc_design_panel").width());
				//$("#pdc_iframe", mainWindow).attr("height", $(".pdc_design_panel")[0].scrollHeight + 10);
				$("#pdc_iframe", mainWindow).css({
					"width": iframeWidth,
					"height" : iframeHeight,
					"left" : (screen.availWidth- iframeWidth) / 2,
					"top" : _ifMarginTop,
					"background" : "white"
				});
				LoadDesign.readyToDesign();
			},
			closeIframe : function() {
				$("#close_iframe").click(function() {
					$("#pdc_iframe", mainWindow).css({"top" : "-100000px"});
				});
			}(),
			readyToDesign : function() {
				$(".loader").hide();
				$(".iframe-container").show();
				top.document.body.scrollTop = top.document.documentElement.scrollTop = 0;
			},
			showSampleImage : function() {
				if($("#sample_images", mainWindow).length) {
					var sampleImageStr = $("#sample_images", mainWindow).val();
					if (sampleImageStr) {
						var sampleImageJson = JSON.parse(sampleImageStr);
						if (sampleImageJson[0].image_result) {
							$('.product-view .product-img-box .product-image img', mainWindow).attr('src', sampleImageJson[0].image_result);
						}
						if (sampleImageJson.length > 1) {
							$('.more-views', mainWindow).remove();
							if($('.product-view .product-img-box .pdp_more_view', mainWindow).length == 0){
								$('.product-view .product-img-box', mainWindow).append('<div class="more-views"><h2>More Views</h2><ul class="pdp_more_view"></ul></div>');
							}else{
								$('.pdp_more_view', mainWindow).html('');
							}
							$.each(sampleImageJson, function(index, image) {
								$('.pdp_more_view', mainWindow).append('<li><img title="' + image.side_name + '" width="56" height="56" src="'+ image.image_result +'" /></li>');
							});
							$('.pdp_more_view li img', mainWindow).click(function(){
								$('.product-view .product-img-box .product-image img', mainWindow).attr('src',$(this).attr('src')); 
							});
						}
					}
				}
			}(),
			reloadPrice : function() {
				/********************************** RELOAD PRICE **********************************/
				if ($("#product_price_config", mainWindow).length) {
					var productPriceConfig = JSON.parse($("#product_price_config", mainWindow).val());
					if (productPriceConfig.productId === undefined) {
						return false;
					}
					var extraPrice = 0;
					if ($("#extra_options_value", mainWindow).length && $("#extra_options_value", mainWindow).val() != "") {
						var extraOptionsValue = JSON.parse($("#extra_options_value", mainWindow).val());
						var sampleCost = extraOptionsValue.items[0].final_price;
						if (sampleCost) {
							extraPrice = parseFloat(sampleCost); 
						}
					}
					productPriceConfig.productPrice = productPriceConfig.productPrice + extraPrice;
					productPriceConfig.productOldPrice = productPriceConfig.productOldPrice + extraPrice;
					parent.optionsPrice = new parent.Product.OptionsPrice(productPriceConfig);
					try {
						parent.optionsPrice.reload();
					} catch(error) {
						console.log(error);
					}
				}
				/********************************** End RELOAD PRICE **********************************/
			}(),
			getDesignPageClick : function() {
				$("#get_design_content").click(function() {
					top.document.body.scrollTop = top.document.documentElement.scrollTop = 0;
					if($(this).hasClass("loaded")) {
						//Show iframe
						$("#pdc_iframe", mainWindow).css({
							"top" : _ifMarginTop
						});
						return false;
					} else {
						$("#pdc_iframe", mainWindow).css({
							"top" : (screen.availHeight / 2) - 150 + "px",
							"left" : (screen.availWidth - 300) / 2 + "px"
						});
					}
					$(this).addClass("loaded");
					LoadDesign.init();
				});
			}(),
			autoClickCustomBtn : function() {
				if($("#pdp_design_action", mainWindow).val() == "design") {
					$("#get_design_content").click();
				}
			}
 		}
 		LoadDesign.autoClickCustomBtn();
	});
</script>